@startuml

rectangle "Сервис отсутствий" {
entity "Отсутствие" as absence {
Ученик
Дата
Причина
Родитель
}
}

rectangle "Сервис оценок" {
entity "Оценка" as mark {
Ученик
Дата
Значение
Сотрудник_школы_учитель
}

entity "Предмет" as subject {
Название
}
}

rectangle "Сервис форума" {
entity "Тема_форума" as topic{
Название
Дата_создания
Автор
}

entity "Сообщение_темы_форума" as message {
Текст
Дата_создания
Автор
}
}






topic *-- message
mark --* subject
subject -[hidden]- absence


@enduml